version: '3'
services:
    api_middleman:
        build: .
        networks:
            api_network:
        ports:
          - "8000"
        environment:
          - API_URL=$API_CONTAINER_NAME_PORT
          - VIRTUAL_PORT=8000
          - VIRTUAL_HOST=${THIS_API_HOSTNAME}
          - LETSENCRYPT_HOST=${THIS_API_HOSTNAME}
        command: tail /dev/null -f
        volumes:
            - ./app:/app/app
            - ./dev.py:/app/main.py
          
networks:
    api_network:
        external:
            name: viewer_default