version: '3'
services:
    api_middleman:
        build: .
        networks:
            api_network:
        ports:
          - "8000"
        environment:
          - API_URL=http://$API_CONTAINER_NAME_PORT
          - APP_URL=localhost
          - VIRTUAL_PORT=8000
          - VIRTUAL_HOST=${THIS_API_HOSTNAME}
          - LETSENCRYPT_HOST=${THIS_API_HOSTNAME}
        command: /start-reload.sh
        volumes:
            - ./app:/app/app

networks:
    api_network:
        external:
            name: ${API_CONTAINER_NETWORK_NAME}